### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by dawesi** [Microsoft/3-in-1-dock#2]
http://meta.stackexchange.com/questions/272956/a-new-code-license-the-mit-this-time-with-attribution-required

Should be simple to implement, but will be required soon, I'd assume some simple comments would be in order before code

**Comment by danchar4** [comment]
Dawesi. I'm confused. What does a StackExchange debate about code licenses have to do with our project released under the MIT license on GitHub? What is the problem you're asking us to solve?
